apiVersion: v1
kind: Service
metadata:
  name: oven-fox-service
  labels:
    run: oven-fox
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 31704
    protocol: TCP
    name: http
  selector:
    run: oven-fox
